### ISSUE TITLE
Errror: i have made little change in this application, have added JPA and Entity,locally it works fine ,while deploying in azure as function while hitting the post request it throws below error, 

### ISSUE THREAD

**Issue by mitesh293** [Azure-Samples/hello-spring-function-azure#20]
2020-08-02T17:42:57.544 [Information] on-parent/spring-cloud-function-web
2020-08-02T17:42:57.544 [Information] 17:42:56.673 [pool-2-thread-4] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Loaded Start Class: class org.springframework.cloud.function.web.RestApplication
2020-08-02T17:42:57.544 [Information] 17:42:56.673 [pool-2-thread-4] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Main class: class org.springframework.cloud.function.web.RestApplication
2020-08-02T17:42:57.545 [Information] 17:42:56.692 [pool-2-thread-4] INFO org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer - Initializing: class org.springframework.cloud.function.web.RestApplication
2020-08-02T17:43:00.026 [Information] .   ____          _            __ _ _
2020-08-02T17:43:00.026 [Information] /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2020-08-02T17:43:00.026 [Information] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2020-08-02T17:43:00.027 [Information] \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2020-08-02T17:43:00.027 [Information] '  |____| .__|_| |_|_| |_\__, | / / / /
2020-08-02T17:43:00.027 [Information] =========|_|==============|___/=/_/_/_/
2020-08-02T17:43:00.500 [Information] :: Spring Boot ::        (v2.2.7.RELEASE)
2020-08-02T17:43:00.501 [Information] 2020-08-02 17:43:00.439  INFO 5372 --- [pool-2-thread-4] o.s.boot.SpringApplication               : Starting application on RD2818786E8DDF with PID 5372 (D:\home\site\wwwroot\lib\spring-cloud-function-web-3.0.6.RELEASE.jar started by RD2818786E8DDF$ in D:\local\Temp\functions\standby\wwwroot)
2020-08-02T17:43:00.501 [Information] 2020-08-02 17:43:00.470  INFO 5372 --- [pool-2-thread-4] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2020-08-02T17:43:03.651 [Information] 2020-08-02 17:43:03.236  INFO 5372 --- [pool-2-thread-4] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2020-08-02T17:43:03.651 [Information] 2020-08-02 17:43:03.492  INFO 5372 --- [pool-2-thread-4] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 219ms. Found 0 JPA repository interfaces.
2020-08-02T17:43:05.789 [Information] 2020-08-02 17:43:05.631  WARN 5372 --- [pool-2-thread-4] o.s.c.support.GenericApplicationContext  : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
2020-08-02T17:43:05.789 [Information] 2020-08-02 17:43:05.690  INFO 5372 --- [pool-2-thread-4] ConditionEvaluationReportLoggingListener :
2020-08-02T17:43:05.789 [Information] Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-02T17:43:05.803 [Information] 2020-08-02 17:43:05.783 ERROR 5372 --- [pool-2-thread-4] o.s.boot.SpringApplication               : Application run failed
2020-08-02T17:43:05.811 [Information] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
2020-08-02T17:43:05.811 [Information] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.811 [Information] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.859 [Information] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.860 [Information] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.860 [Information] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.860 [Information] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.860 [Information] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:117) [spring-cloud-function-context-3.0.6.RELEASE.jar:3.0.6.RELEASE]
2020-08-02T17:43:05.861 [Information] at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:80) [spring-cloud-function-adapter-azure-3.0.6.RELEASE.jar:3.0.6.RELEASE]
2020-08-02T17:43:05.861 [Information] at com.example.HelloHandler.saveEmployee(HelloHandler.java:49) [hello-spring-function-azure.jar:na]
2020-08-02T17:43:05.862 [Information] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
2020-08-02T17:43:05.862 [Information] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
2020-08-02T17:43:05.867 [Information] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
2020-08-02T17:43:05.868 [Information] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
2020-08-02T17:43:05.868 [Information] at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22) [azure-functions-java-worker.jar:1.5.3]
2020-08-02T17:43:05.868 [Information] at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54) [azure-functions-java-worker.jar:1.5.3]
2020-08-02T17:43:05.868 [Information] at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:52) [azure-functions-java-worker.jar:1.5.3]
2020-08-02T17:43:05.868 [Information] at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33) [azure-functions-java-worker.jar:1.5.3]
2020-08-02T17:43:05.868 [Information] at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10) [azure-functions-java-worker.jar:1.5.3]
2020-08-02T17:43:05.868 [Information] at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45) [azure-functions-java-worker.jar:1.5.3]
2020-08-02T17:43:05.868 [Information] at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92) [azure-functions-java-worker.jar:1.5.3]
2020-08-02T17:43:05.868 [Information] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
2020-08-02T17:43:05.868 [Information] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_232]
2020-08-02T17:43:05.868 [Information] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
2020-08-02T17:43:05.869 [Information] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
2020-08-02T17:43:05.869 [Information] at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
2020-08-02T17:43:05.869 [Information] Caused by: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
2020-08-02T17:43:05.869 [Information] at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:641) ~[spring-orm-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.869 [Information] at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.preparePersistenceUnitInfos(DefaultPersistenceUnitManager.java:463) ~[spring-orm-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.869 [Information] at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.afterPropertiesSet(DefaultPersistenceUnitManager.java:444) ~[spring-orm-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.869 [Information] at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:328) ~[spring-orm-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.869 [Information] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.869 [Information] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.869 [Information] ... 31 common frames omitted
2020-08-02T17:43:05.869 [Information] Caused by: java.io.FileNotFoundException: class path resource [] cannot be resolved to URL because it does not exist
2020-08-02T17:43:05.870 [Information] at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.870 [Information] at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:637) ~[spring-orm-5.2.6.RELEASE.jar:5.2.6.RELEASE]
2020-08-02T17:43:05.870 [Information] ... 36 common frames omitted
2020-08-02T17:43:05.986 [Error] Executed 'Functions.saveEmployee' (Failed, Id=87a963a8-df30-4360-ba37-53e906c4bb6b, Duration=12924ms)
Result: Failure
Exception: FileNotFoundException: class path resource [] cannot be resolved to URL because it does not exist
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:52)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:117)
	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:80)
	at com.example.HelloHandler.saveEmployee(HelloHandler.java:49)
	... 16 more
Caused by: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:641)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.preparePersistenceUnitInfos(DefaultPersistenceUnitManager.java:463)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.afterPropertiesSet(DefaultPersistenceUnitManager.java:444)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:328)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 31 more
Caused by: java.io.FileNotFoundException: class path resource [] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:637)
	... 36 more
2020-08-02T17:43:06.035 [Error] Executed 'Functions.saveEmployee' (Failed, Id=87a963a8-df30-4360-ba37-53e906c4bb6b, Duration=12924ms)
Result: Failure
Exception: FileNotFoundException: class path resource [] cannot be resolved to URL because it does not exist
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:52)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:117)
	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:80)
	at com.example.HelloHandler.saveEmployee(HelloHandler.java:49)
	... 16 more
Caused by: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:641)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.preparePersistenceUnitInfos(DefaultPersistenceUnitManager.java:463)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.afterPropertiesSet(DefaultPersistenceUnitManager.java:444)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:328)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 31 more
Caused by: java.io.FileNotFoundException: class path resource [] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195)
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:637)
	... 36 more

=======================================================
where i am wrong i don't know ,full git code is attached here

https://github.com/mitesh293/AzureSpringDataJpa

**Comment by mitesh293** [comment]
@jdubois There is not much document provided on Microsoft azure document as well

Can you please suggest me some thing on this?

full code is here ,

https://github.com/mitesh293/AzureSpringDataJpa

**Comment by jdubois** [comment]
I'm sorry but you modified the application to use JPA, and then have a configuration issue in JPA (as can be seen in the logs), so this definitely is not a bug in this repo.
Because of its start-up time, I would not recommend using JPA with Azure Functions (unless you use something like Quarkus + GraalVM, but that's a whole different story).
Reading the exception, you have a "java.io.FileNotFoundException" while reading your persistence context - I'm guessing you don't have a persistence.xml file, or that it's not in the correct directory.
