### ISSUE TITLE
System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Failure Exception: NoSuchElementException: No value present Stack: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by SelvamRajendrn** [Azure-Samples/hello-spring-function-azure#23]
I am getting below exception when I execute this example

Azure Functions Core Tools (3.0.2630 Commit hash: beec61496e1c5de8aa4ba38d1884f7b48233a7ab)
Function Runtime Version: 3.0.13901.0

[10/5/2020 7:42:24 PM] Executing HTTP request: {
[10/5/2020 7:42:24 PM]   "requestId": "a5ca11b1-b512-4516-8f92-2eefbc63d164",
[10/5/2020 7:42:24 PM]   "method": "GET",
[10/5/2020 7:42:24 PM]   "uri": "/api/hello"
[10/5/2020 7:42:24 PM] }
[10/5/2020 7:42:24 PM] Executing 'Functions.hello' (Reason='This function was programmatically called via the host APIs.', Id=9fc63423-3bdd-4ce1-ae48-c58d97827064)
[10/5/2020 7:42:24 PM] 15:42:24.545 [pool-2-thread-1] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Main class: class com.example.HelloFunction
[10/5/2020 7:42:24 PM] Executed 'Functions.hello' (Failed, Id=9fc63423-3bdd-4ce1-ae48-c58d97827064)
[10/5/2020 7:42:24 PM] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Failure
Exception: NoSuchElementException: No value present
Stack: java.lang.reflect.InvocationTargetException
[10/5/2020 7:42:24 PM]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10/5/2020 7:42:24 PM]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10/5/2020 7:42:24 PM]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10/5/2020 7:42:24 PM]  at java.lang.reflect.Method.invoke(Method.java:498)
[10/5/2020 7:42:24 PM]  at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[10/5/2020 7:42:24 PM]  at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
[10/5/2020 7:42:24 PM]  at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
[10/5/2020 7:42:24 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[10/5/2020 7:42:24 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[10/5/2020 7:42:24 PM]  at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[10/5/2020 7:42:24 PM]  at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[10/5/2020 7:42:24 PM]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10/5/2020 7:42:24 PM]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10/5/2020 7:42:24 PM]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10/5/2020 7:42:24 PM]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10/5/2020 7:42:24 PM]  at java.lang.Thread.run(Thread.java:748)
[10/5/2020 7:42:24 PM] Caused by: java.util.NoSuchElementException: No value present
[10/5/2020 7:42:24 PM]  at java.util.Optional.get(Optional.java:135)
[10/5/2020 7:42:24 PM]  at com.example.HelloHandler.execute(HelloHandler.java:20)
[10/5/2020 7:42:24 PM]  ... 16 more
[10/5/2020 7:42:24 PM] .
[10/5/2020 7:42:24 PM] Executed HTTP request: {
[10/5/2020 7:42:24 PM]   "requestId": "a5ca11b1-b512-4516-8f92-2eefbc63d164",
[10/5/2020 7:42:24 PM]   "method": "GET",
[10/5/2020 7:42:24 PM]   "uri": "/api/hello",
[10/5/2020 7:42:24 PM]   "identities": [
[10/5/2020 7:42:24 PM]     {
[10/5/2020 7:42:24 PM]       "type": "WebJobsAuthLevel",
[10/5/2020 7:42:24 PM]       "level": "Admin"
[10/5/2020 7:42:24 PM]     }
[10/5/2020 7:42:24 PM]   ],
[10/5/2020 7:42:24 PM]   "status": 500,
[10/5/2020 7:42:24 PM]   "duration": 276
[10/5/2020 7:42:24 PM] }

**Comment by SelvamRajendrn** [comment]
never mind. I used get method instead post
